version: '3.8'

services:
  postgres-ouaf:
    image: postgres:14
#    restart: always
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  ouaf:
    build: .
#    user: "{UID}:${GID}"
#    command: python manage.py runserver 0.0.0.0:8000
#    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres-ouaf
    environment:
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
    env_file:
      - .env
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:

