# Generated by Django 5.2.5 on 2025-08-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouaf_app', '0002_organisationchartentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_publish_event', 'Can publish an event')]},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('can_change_user_role', 'Can change user roles')]},
        ),
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
