# Generated by Django 5.2.5 on 2025-08-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouaf_app', '0003_alter_event_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_volunteer',
        ),
    ]
