# Generated by Django 5.2.5 on 2025-08-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ouaf_app', '0006_activite'), ('ouaf_app', '0007_alter_activite_image')]

    dependencies = [
        ('ouaf_app', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/activities')),
            ],
        ),
    ]
