# Generated by Django 5.2.5 on 2025-08-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ouaf_app', '0008_remove_organisationchartentry_personid_and_more'), ('ouaf_app', '0009_organisationchartentry_role')]

    dependencies = [
        ('ouaf_app', '0006_activite_squashed_0007_alter_activite_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationchartentry',
            name='personId',
        ),
        migrations.RemoveField(
            model_name='organisationchartentry',
            name='text',
        ),
        migrations.AddField(
            model_name='organisationchartentry',
            name='description',
            field=models.TextField(default='lol', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationchartentry',
            name='first_name',
            field=models.CharField(default='lol', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationchartentry',
            name='last_name',
            field=models.CharField(default='lol', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisationchartentry',
            name='role',
            field=models.CharField(default='lol', max_length=26),
            preserve_default=False,
        ),
    ]
