# Generated by Django 5.2.5 on 2025-08-27 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouaf_app', '0008_remove_organisationchartentry_personid_and_more_squashed_0009_organisationchartentry_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreignId', models.UUIDField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='death',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AnimalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(upload_to='animals/media')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ouaf_app.animal')),
            ],
            options={
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
    ]
