# Generated by Django 5.2.5 on 2025-08-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouaf_app', '0010_activitycategory_delete_service_activite_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ouaf_app.activitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, upload_to='activities/media')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ouaf_app.activity')),
            ],
            options={
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Activite',
        ),
    ]
