# Generated by Django 5.2.5 on 2025-08-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouaf_app', '0011_activity_activitymedia_delete_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ouaf_app.activitycategory'),
        ),
    ]
