# Generated by Django 5.2.5 on 2025-09-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouaf_app', '0012_alter_activity_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(upload_to='animals/media')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ouaf_app.animal')),
            ],
            options={
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
    ]
