# Generated by Django 5.2.5 on 2025-09-19 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouaf_app', '0014_animal_description_alter_animal_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_publish_event', 'Peut publier un événement')]},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('can_change_user_role', 'Peut changer les rôles utilisateurs')]},
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ouaf_app.activitycategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='image',
            field=models.ImageField(upload_to='images/categories', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='activitymedia',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ouaf_app.activity', verbose_name='Activité'),
        ),
        migrations.AlterField(
            model_name='activitymedia',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende'),
        ),
        migrations.AlterField(
            model_name='activitymedia',
            name='file',
            field=models.FileField(blank=True, upload_to='activities/media', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='activitymedia',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='activitymedia',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='death',
            field=models.DateField(blank=True, null=True, verbose_name='Date de décès'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(default='name', max_length=100, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='pet_amount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Nombre de caresses'),
        ),
        migrations.AlterField(
            model_name='animalmedia',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende'),
        ),
        migrations.AlterField(
            model_name='animalmedia',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='animalmedia',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=1000, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attendees2person', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.DurationField(verbose_name='Durée'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organiser2person', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.CharField(max_length=500, verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='event',
            name='until',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='amount',
            field=models.FloatField(verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='paymentDate',
            field=models.DateTimeField(verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='memberpayment',
            name='personId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Personne'),
        ),
        migrations.AlterField(
            model_name='organisationchartentry',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organisationchartentry',
            name='first_name',
            field=models.CharField(max_length=1000, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='organisationchartentry',
            name='last_name',
            field=models.CharField(max_length=1000, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='organisationchartentry',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/organisationChart', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='organisationchartentry',
            name='role',
            field=models.CharField(max_length=26, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=1000, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='person',
            name='newsletter_subscription',
            field=models.BooleanField(default=False, verbose_name='Abonnement à la newsletter'),
        ),
    ]
