# Generated by Django 5.2.6 on 2025-09-21 13:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouaf_app', '0015_alter_event_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='FR', verbose_name='Téléphone'),
        ),
    ]
