# Generated by Django 5.2.6 on 2025-09-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouaf_app', '0016_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationchartentry',
            name='role',
            field=models.CharField(max_length=128, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un utilisateur avec cet email existe déjà.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
